### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by Adib128** [uilibrary/Stocky-Issues-and-Feature-request#105]
Hello, I started installing the app on my xampp server, when I reach to the last step of the installation it shows me an error 419 cannot access to the page. Cany you help me please

**Comment by hamzakifani** [comment]
Please follow the installation guide. You will not face any problem , thank you

**Comment by ibrafayez** [comment]
I followed the installation guide I got an error

<img width="917" alt="Screen Shot 2021-05-26 at 6 49 00 PM" src="https://user-images.githubusercontent.com/44995398/119691282-1cd1b300-be53-11eb-8aeb-f82d0d731472.png">

**Comment by naime-hossain** [comment]
@Adib128 @Adib128 hey man, you need to send a refund request because we don't have the option to refund a specific buyer, I said it before, instead of send a refund request you asking me to send a refund and you gave us a bad rating intentionally, its your fault you are not able to use our product. please update the rating and send a refund request. thank you
