### ISSUE TITLE
YOUR TEAM NEED TO CREATE A REAL HOW TO VIDEO

### ISSUE THREAD

**Issue by hificom** [uilibrary/Stocky-Issues-and-Feature-request#131]
YOUR TEAM NEED TO CREATE A REAL HOW TO VIDEO

AND BETTER DOCUMENTATION

ITS TAKEN ME HOURS JUST TO TRY TO FIGURE OUT WHAT THIS APPLICATION DOES.

IT'S A BIG WASTE OF MY TIME!!1

**Comment by hamzakifani** [comment]
It seems you do not understand how work system inventory . To create sale you have to purchase the product first. Because the sales comes when you have stock.

sale can only occur when you have stock. Without stock how can you sale product? So purchase that product first. Then you can make sale. Thank you

create purchase via http://stocky.ui-lib.com/app/purchases/store

**Comment by naime-hossain** [comment]
> YOUR TEAM NEED TO CREATE A REAL HOW TO VIDEO
> 
> AND BETTER DOCUMENTATION
> 
> ITS TAKEN ME HOURS JUST TO TRY TO FIGURE OUT WHAT THIS APPLICATION DOES.
> 
> IT'S A BIG WASTE OF MY TIME!!1

It's clear in the demo and description, it is an inventory management application with POS. By the way, thank you for the suggestions we will add a video soon.
