### ISSUE TITLE
Incorrect Profit displaying 

### ISSUE THREAD

**Issue by narayanwork92** [uilibrary/Stocky-Issues-and-Feature-request#159]
It’s showing wrong profit. I think calculation might wrong. 
Sales, Payments received, Profit Net showing same amount. Profit must be calculated from (price - cost) * No.of Quantity. it's better if we get a fix asap

**Comment by hamzakifani** [comment]
Hi,
=> income = payment sales + payment return purchases
=> expense = Payment Purchase + Payment Sale Returns + expenses in warehouse
=> profit = income – expense


Profit loss depends on purchase and sale, not on cost and price. If you purchase a product but not sold yet then the profit should be negative because you are still not making money.

**Comment by hamzakifani** [comment]
Fixed
