### ISSUE TITLE
SQL Error in installation wizard

### ISSUE THREAD

**Issue by saturnobit** [uilibrary/Stocky-Issues-and-Feature-request#24]
Hello everyone, today I bought socky and started the deployment of the solution in my hostgator web hosting, I created a user for the database and the database to later start the configuration on the web. once I finish the form I get a blank window with the following error:

SQLSTATE [HY000] [1045] Access denied for user 'bitclust_app_dhdistribuidora' @ 'localhost' (using password: YES) (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')

**Comment by saturnobit** [comment]
https://user-images.githubusercontent.com/82850635/115318554-933c1080-a143-11eb-8414-2e65adb8e10c.mp4

**Comment by saturnobit** [comment]
https://user-images.githubusercontent.com/82850635/115318599-a7800d80-a143-11eb-9f74-c45e2eaeaa82.mp4

**Comment by hamzakifani** [comment]
The reason of Access denied for user  is caching-issue

1) just change these things in the .env file of your root folder.
![image](https://user-images.githubusercontent.com/50219942/115319943-6a7e4000-a170-11eb-9d61-a16558bb6ecd.png)

DB_DATABASE=your_db_name
DB_USERNAME=your_db_user_name
DB_PASSWORD='your_db_password'

2) You must ‍‍restart your web server.. and refresh your page and you have done

3) if your problem is not resolved , remove the file config.php in the bootstrap/cache/config.php

**Comment by naime-hossain** [comment]
Hello @saturnobit are you able to fix the issue? let us know. thank you

**Comment by saturnobit** [comment]
Hello, in any hours I will try this solución and comeback with you.

**Comment by saturnobit** [comment]
I checked my files but I don't have .env file :(

**Comment by saturnobit** [comment]
![Screenshot from 2021-04-20 19-29-54](https://user-images.githubusercontent.com/82850635/115479790-cbf4ec00-a20e-11eb-87b1-b762aaf20a35.png)

**Comment by saturnobit** [comment]
Don't worry I found it. It's one hide file and all ready.

**Comment by hamzakifani** [comment]
are you able to fix the issue? let us know. thank you

**Comment by saturnobit** [comment]
Perfect! All it's ready! (:

**Comment by hamzakifani** [comment]
Great Job. if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items Your review will motivate us thank you

**Comment by saturnobit** [comment]
I know this itsn't about the issue but what is the configuration for set quantity about products?

**Comment by hamzakifani** [comment]
You can add product quantity via Adjustments https://stocky.ui-lib.com/app/adjustments/store, for this, you need to purchase the product first.

**Comment by naime-hossain** [comment]
Hope your issue is fixed and let us know if you need any further help, I am closing the issue for now :) 

Great Job. if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items Your review will motivate us to thank you
