### ISSUE TITLE
No Exsisiting customer ditect  -> Prevent Dublicate customer creation 

### ISSUE THREAD

**Issue by AntZ-Dush** [uilibrary/Stocky-Issues-and-Feature-request#28]
In the customer add  section, I can add the same customer again and again. but it's not the right way. if we add someone repeatedly system should detect that and give us an error message

**Comment by naime-hossain** [comment]
Hello, @AntZ-Dush we  Add this feature, you will get it StockyV2.1.0 version which will be released tomorrow. 
if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by naime-hossain** [comment]
I am closing this issue as this fixed with stocky@2.0.0 . if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you

**Comment by AntZ-Dush** [comment]
Thank you very much

**Comment by naime-hossain** [comment]
> Thank you very much

if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
