### ISSUE TITLE
Where to edit files to change Verbiage and Menu Navigation text

### ISSUE THREAD

**Issue by hificom** [uilibrary/Stocky-Issues-and-Feature-request#314]
======================
1 - website…/app/People/Customers >Create

I want to change the “Email” field to “PO #” This should also change in the sales invoice PDF as well Where do I make those changes?

======================
2 - website…/app/sales/list#

A] I want to change “Customer List, Supplier List, and User List” text to “Buyers” “Suppliers” and “Management”

B]  where can we change the Reference Number. It is currently Sales SL_1114 We would like to change it to BN_2120001

Where do I make those changes?

======================= 
3. REMOVE / HIDE SIDE MENU NAVIGATION

I would like to remove or hide some of the left tabs / icons For example, I would like to remove the “Doc” tab from the application…

4. REORDER MENU NAVIGATION

I would also like to reorder the side menu list based on what I use most… Is this possible?

For example we would like:

- Dashboard
- People
- Products
- Sales
- Reports
- Settings

--- ect. ---

**Comment by hificom** [comment]
I like the email - but we also need to include Purchase Order in our invoice --- Where can we make the changes?

![Screen Shot 2021-08-06 at 11 29 28 PM](https://user-images.githubusercontent.com/85292687/128601383-49c41a65-a5c5-4e2a-8137-f12761fbde25.JPG)
![Screen Shot 2021-08-06 at 11 28 47 PM](https://user-images.githubusercontent.com/85292687/128601384-1fe9e8bd-51d8-44f4-89e1-87afbe1b60a8.JPG)
![Screen Shot 2021-08-06 at 11 28 34 PM](https://user-images.githubusercontent.com/85292687/128601385-96764d82-2788-4191-a00d-2cf816fb20fc.JPG)

**Comment by Vertex21** [comment]
I'm not affiliated in any way with the makers of this software, but I do work with it personally for my company and edit it often. Ideally you would want to have a development machine capable of compiling NodeJS projects like this one. You make your changes in the .vue template files but in your case you would also need to do some work in the javascript of the vue template files because the Email field is a special field that validates the formatting of the entered data against what a proper email address format should be.
After making your code changes you would run:
npm install (to load all the node modules from the package.json file)
npm run watch (if you wanted to make edits and then have the project auto re-compile after the changes so you can test the results)
npm run prod (when you are sure of your changes and want to prepare the project for production)
You would then follow the project update documentation they have provided and you should be good to go!

**Comment by deansga** [comment]
Can you remove the docs menu with some simple css/html code?

If so which file can I edit to remove the Docs from the left menu

thanks

**Comment by Vertex21** [comment]
No, deansga.. Being it's a Laravel/Vue app you have to recompile the project after you edit the code. Well to do it properly anyway. You could possible add some CSS to the globals.css file in the ./public/css folder to count down the number of <li> elements in the nav bar and do a display:none on it.

**Comment by hificom** [comment]
@Vertex21 Thank you for your insight.
I can not believe that the makers of the software would have made it extremely difficult for dev. to make these types of changes.  
However, thank you for letting me know this.  I would hope to hire you if I could.

**Comment by naime-hossain** [comment]
We will remove doc from the source code menu In next update . thank you
