### ISSUE TITLE
Getting NPM RUN DEV and NPM RUN PROD Errors after making Changes

### ISSUE THREAD

**Issue by niendoo** [uilibrary/Stocky-Issues-and-Feature-request#351]
Please see screencast for replication of issue as I tried to comment out the docs sidebar item
https://www.awesomescreenshot.com/video/5226274?key=d24c65813640368759891d8b5a8c68a6

**Comment by hamzakifani** [comment]
Hello , 
I think you don't know how vuejs work , 
so you need first install node js with command
1) npm install
after run 
2) npm run prod
thanks

**Comment by niendoo** [comment]
I did exactly that and it didn't work. I was even forced to install webpack
cli yet it still didn't work. It looks like your latest update contains
outdated files. I even did npm audit fix --force yet still didn't work!

**Comment by niendoo** [comment]
Further Issues I have discovered.
1. When creating barcodes, it generates black barcodes.
2. When creating products, there's no field to add product Quantity and when you go to Adjustments to do that too, the search field does not show products when searched.
3. When creating sales either via sales or Pos menu, products do not show up when searched. 
I am adding a screencast to this so that you can rectify these issues asap. Also kindly go through the system well for me. Thanks.
https://www.awesomescreenshot.com/video/5282655?key=a1410145f4360346fce4c6bd1a359c71

**Comment by hamzakifani** [comment]
Hello ,
1> please select the correct type symobologic .

2> when you create the product you need to purchase it 
To add adjustment you have to purchase the product first. Because the adjustments comes when you have stock.

Adjustment can only occur when you have stock. Without stock how can you adjust quantity? So purchase that product first. Then you can make adjustment. Thank you

create purchase via http://stocky.ui-lib.com/app/purchases/store

3> please check if product has stock . How can you sale the product without stock ?

Thank you

**Comment by niendoo** [comment]
Ok, I will do that. But please kindly check your inbox for the twilio api
issue. Thank you.

**Comment by hamzakifani** [comment]
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you 


Giving Feedback On Items
https://help.market.envato.com
