### ISSUE TITLE
Paid and Due not showing on PDF print for partial sale

### ISSUE THREAD

**Issue by ab-ashagrie** [uilibrary/Stocky-Issues-and-Feature-request#403]
@hamzakifani Hey man, so you said this would be fixed on the update that just rolled out but it wasn't. and it's quite frustrating. So if you could give me a quick fix on how I can make the PDF print out Paid and Due amount for partial sale just as it does on the invoice it would be great

**Comment by hamzakifani** [comment]
Hello , 
We have a lot of features in our queue . We will fix all issues . Thanks

**Comment by ab-ashagrie** [comment]
This is not a new feature but a bug you said would be fixed in your latest update. It's not fixed and I need to fix it right away so just tell me which files to alter and how.

**Comment by hamzakifani** [comment]
This issue fixed in latest version 3.9.0
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
