### ISSUE TITLE
Expense Delete

### ISSUE THREAD

**Issue by ab-ashagrie** [uilibrary/Stocky-Issues-and-Feature-request#407]
I deleted some expenses and they get deleted from the expenses page but are still taken into calculation in the profit report. How can I solve this ?

**Comment by hamzakifani** [comment]
We will check this and let you know soon . Thanks

**Comment by ab-ashagrie** [comment]
Alright,I'll be waiting.

**Comment by hamzakifani** [comment]
This issue fixed in latest version 3.9.0
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
