### ISSUE TITLE
Discount or shipping form has no default value 0 if the form is empty

### ISSUE THREAD

**Issue by zebhi** [uilibrary/Stocky-Issues-and-Feature-request#414]
I realized that when I input discount or shipping and then I deleted this and leave it blank, the Grand Total value not back to actually total price.

Perhaps, You can check this. I just try it on the POS Page. May be you need to check on another page that have this feature too.

![image](https://user-images.githubusercontent.com/7016790/143378730-f23c63a8-ba76-49b3-b09d-11e1fb93fd30.png)

![image](https://user-images.githubusercontent.com/7016790/143379355-dff0ef2e-1584-46b2-bc21-5528b5c1095d.png)

**Comment by hamzakifani** [comment]
We will check this issue . Thanks

**Comment by hamzakifani** [comment]
This issue fixed in latest version 3.9.0 .
if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
