### ISSUE TITLE
Change default background image on login page

### ISSUE THREAD

**Issue by saturnobit** [uilibrary/Stocky-Issues-and-Feature-request#43]
Hello there,
I would like to know if exist one way to change the default wallpaper on the login page.

![Screenshot from 2021-04-25 17-48-34](https://user-images.githubusercontent.com/82850635/116012158-79407900-a5ee-11eb-9305-b4d15f2a2dcd.png)

**Comment by hamzakifani** [comment]
1) download nodejs
2) run : npm install
3) edit resources\src\app\views\sessions\SignIn.vue file
4) npm run watch + npm run prod

please do these and let me know. thank you

**Comment by saturnobit** [comment]
Perfect! It's works🤗

**Comment by hamzakifani** [comment]
Hope your issue is fixed and let us know if you need any further help.

Great Job. if you like our work, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items Your review will motivate us to thank you

**Comment by naime-hossain** [comment]
Hello, I am closing the Issue, if you still have any issues let us know. if you like our work and support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items Your review will motivate us to thank you
