### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by saturnobit** [uilibrary/Stocky-Issues-and-Feature-request#44]
I don't want to show the item dashboard to all users, does it exist one way for hide the main dashboard in any users?

**Comment by saturnobit** [comment]
![IMG20210425203708.jpg](https://user-images.githubusercontent.com/82850635/116017732-0511cf80-a606-11eb-8210-358128e0d888.jpg)

**Comment by saturnobit** [comment]
I don't show too, the documentation item. Added one picture.

**Comment by saturnobit** [comment]
![IMG20210425203954.jpg](https://user-images.githubusercontent.com/82850635/116017891-689bfd00-a606-11eb-98ba-ec03bf7c2a78.jpg)

**Comment by hamzakifani** [comment]
Hi , at the moment there is no option for hide dashboard but we will add this option in future.  

Create a role in http://stocky.ui-lib.com/app/Settings/Permissions/store
And if you checkor uncheck the "show all records".  so user only see their records. Thank you

**Comment by naime-hossain** [comment]
I am closing the issue and hope your problem is solved. 

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you
