### ISSUE TITLE
Cash Received And Cash to return

### ISSUE THREAD

**Issue by Bytepie** [uilibrary/Stocky-Issues-and-Feature-request#58]
In payout, there is only option of validating the payment. but there is no option for simple and yet very important feature of POS. Which is how much cash has been received and how much change should be given back to the customer.

All POS have this feature, I didn't see demo very carefully than I should have.
This simple front end functionality saves time and reduce errors of calculating amounts yourself.

**Comment by Bytepie** [comment]
I believe there is already an entry for this issue.

**Comment by naime-hossain** [comment]
We will review the issue that's why reponed it. thank you for your suggestions :) 

if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
